# Generated by Django 6.0.4 on 2026-05-31 16:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nama Engineer/Tim', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_team', models.CharField(default='Intelligence Engineer', max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_file', models.FileField(upload_to=core.models.submission_file_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('detected_data_type', models.CharField(choices=[('image', 'Gambar'), ('tabular', 'Tabular (CSV/Excel)'), ('text', 'Teks'), ('numeric', 'Numerik'), ('mixed', 'Campuran'), ('unknown', 'Belum Terdeteksi')], default='unknown', max_length=20)),
                ('extra_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('current_stage', models.IntegerField(choices=[(0, 'Problem Framing & IPO'), (1, 'Definisi Dataset'), (2, 'Pemrosesan Data'), (3, 'Perencanaan Model'), (4, 'Pelatihan & Testing'), (5, 'Refining Model')], default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending (Belum Diproses)'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai (6 Tahap Beres)'), ('sent', 'Sudah Dikirim ke Tim Lain'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('started_processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('api_key_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.apikey')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intelligence Submission',
                'verbose_name_plural': 'Intelligence Submissions',
                'ordering': ['-received_at'],
            },
        ),
    ]
